Stop spamming our contact form with buildfarm notifications
foxglove/ros-foxglove-bridge pull request #104
Opened 2022-12-02 03:18 UTC by amacneil

2022-12-02 03:34 UTC, jtbandes requested changes
I think we should probably use the ros-tooling@foxglove.dev group which we made for this purpose. Whether John & Achim want to be listed individually as author/maintainer is up to them; personally I've liked to maintain [plausible deniability](https://github.com/foxglove/schemas/blob/main/ros_foxglove_msgs/package.xml#L13) for my own involvement in our published packages 😄

2022-12-02 12:28 UTC, achim-k commented
I believe that emails are only sent to maintainers, not authors. So #70 should have fixed this problem. Old release builds might still send emails to contact@foxglove.com but those should fade out soon. 

> I think we should probably use the ros-tooling@foxglove.dev group which we made for this purpose

That's a good idea. Maybe we could make it even ros-tooling+foxglove_bridge@foxglove.dev, so mail traffic for that project can be forwarded easily to the corresponding developers

2022-12-04 21:42 UTC, amacneil commented
I don't mind where they get sent, but contact@foxglove.dev should not be hooked up to any automated notifications (it goes to our sales inbox). We were still getting like 20 emails/day as of Thursday so I don't think https://github.com/foxglove/ros-foxglove-bridge/pull/70 worked.

2022-12-05 17:30 UTC, jtbandes approved these changes

2022-12-05 17:30 UTC, merged