Switch devcontainer to ROS2 humble
foxglove/ros-foxglove-bridge pull request #124
Opened 2022-12-19 21:46 UTC by achim-k

**Public-Facing Changes**
None

**Description**
ROS2 `galactic` is EOL since December 9th 2022. This PR changes the devcontainer to be based on ROS 2 `humble`. 

With that change, the devcontainer does not support ROS1 anymore. `humble` is supported on Ubuntu focal (Tier 3), but it needs to be compiled from source and I don't think it is worth the effort. Instead, for ROS1 development it is recommended to mount the workspace into a container and attach to the container with VsCode

2022-12-19 22:04 UTC, jtbandes approved these changes

2022-12-20 20:15 UTC, jhurliman requested changes
> Instead, for ROS1 development it is recommended to mount the workspace into a container and attach to the container with VsCode

I don't see any instructions in the README on what this means or how to do it

2022-12-20 20:18 UTC, jhurliman commented
I'm -1 on this change. The current setup of a single container for ROS 1 and ROS 2 makes it very convenient to develop for both platforms. Migrating off the EOL Galactic is a nice goal, but if the cost is a hampered workflow, I don't think it's worth it.

2022-12-22 17:30 UTC, achim-k commented
> I'm -1 on this change. The current setup of a single container for ROS 1 and ROS 2 makes it very convenient to develop for both platforms. Migrating off the EOL Galactic is a nice goal, but if the cost is a hampered workflow then I don't think it's worth it.

What do you propose? Continue with the existing devcontainer?

2022-12-22 20:57 UTC, jhurliman commented
> > I'm -1 on this change. The current setup of a single container for ROS 1 and ROS 2 makes it very convenient to develop for both platforms. Migrating off the EOL Galactic is a nice goal, but if the cost is a hampered workflow then I don't think it's worth it.
> 
> What do you propose? Continue with the existing devcontainer?

Yes

2023-01-03 14:54 UTC, closed without merging