Update README.md ROS2 launch file snippet
foxglove/ros-foxglove-bridge pull request #243
Opened 2023-07-07 00:30 UTC by memtech3

### Public-Facing Changes

README updated with correct example for ROS2 launch file

### Description

ROS2 launch file snippet in README.md had incorrect path to foxglove bridge launch file ` <include file="$(find-pkg-share foxglove_bridge)/launch/foxglove_bridge_launch.xml">`. Path should be `  <include file="$(find-pkg-share foxglove_bridge)/foxglove_bridge_launch.xml">`

2023-07-07 00:30 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/foxglove/ros-foxglove-bridge?pullRequest=243) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/foxglove/ros-foxglove-bridge?pullRequest=243) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/foxglove/ros-foxglove-bridge?pullRequest=243) it.</sub>

2023-07-07 00:31 UTC, memtech3 commented
Fixes #242

2023-07-07 00:39 UTC, memtech3 commented
`ROS Melodic Test` fails during step `make melodic-test` with message 
```
ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
foxglove_bridge: Cannot locate rosdep definition for [ros_babel_fish]
The command '/bin/sh -c . /opt/ros/$ROS_DISTRO/setup.sh &&     apt-get update && rosdep update && rosdep install -y       --from-paths         src       --ignore-src     && rm -rf /var/lib/apt/lists/*' returned a non-zero code: 1
make: *** [Makefile:13: melodic] Error 1

Error: Process completed with exit code 2.
```
Is this a foxglove_bridge bug?

2023-07-07 13:00 UTC, achim-k requested changes
Thanks for the contribution!

While this change is technically correct, I think it would be better to fix the [install rule](https://github.com/foxglove/ros-foxglove-bridge/blob/e336bbc327ec62e18d666f2db248207979c06f57/CMakeLists.txt#L258-L260) by removing the trailing slash on line 258. The launch file should be installed in the `launch` directory, but the current install rules installed it in the package share root directory.

https://github.com/foxglove/ros-foxglove-bridge/blob/e336bbc327ec62e18d666f2db248207979c06f57/CMakeLists.txt#L258-L260

2023-07-07 13:02 UTC, achim-k commented
> `ROS Melodic Test` fails during step `make melodic-test` with message
> 
> ```
> ERROR: the following packages/stacks could not have their rosdep keys resolved
> to system dependencies:
> foxglove_bridge: Cannot locate rosdep definition for [ros_babel_fish]
> The command '/bin/sh -c . /opt/ros/$ROS_DISTRO/setup.sh &&     apt-get update && rosdep update && rosdep install -y       --from-paths         src       --ignore-src     && rm -rf /var/lib/apt/lists/*' returned a non-zero code: 1
> make: *** [Makefile:13: melodic] Error 1
> 
> Error: Process completed with exit code 2.
> ```
> 
> Is this a foxglove_bridge bug?

No, this is due to `melodic` being EOL. I have pushed a [commit](https://github.com/foxglove/ros-foxglove-bridge/pull/232/commits/dbfd38485a3ec52cf49f7164015af44b81658b12) that adds `--include-eol-distros` to `rosdep update` but it's not merged yet.

2023-07-12 01:12 UTC, memtech3 commented
> Thanks for the contribution!
> 
> While this change is technically correct, I think it would be better to fix the [install rule](https://github.com/foxglove/ros-foxglove-bridge/blob/e336bbc327ec62e18d666f2db248207979c06f57/CMakeLists.txt#L258-L260) by removing the trailing slash on line 258. The launch file should be installed in the `launch` directory, but the current install rules installed it in the package share root directory.
> 
> https://github.com/foxglove/ros-foxglove-bridge/blob/e336bbc327ec62e18d666f2db248207979c06f57/CMakeLists.txt#L258-L260

I've updated my branch with that change

2023-07-12 01:18 UTC, memtech3 commented
Change might have made the CI tests failed, investigating

2023-07-12 13:29 UTC, achim-k commented on CMakeLists.txt
> +      DESTINATION share/${PROJECT_NAME}
I think you have to remove the trailing slash one line above (L258)

2023-07-12 13:41 UTC, achim-k commented
I have added the required change. Thanks for your contribution @memtech3!

2023-07-12 13:46 UTC, achim-k approved these changes

2023-07-12 13:46 UTC, merged

2023-07-12 15:29 UTC, memtech3 commented
> I have added the required change. Thanks for your contribution @memtech3!

Thanks! Can you explain the cmake behavior? I'm a little new to C++ and ROS2